apiVersion: "cluster.k8s.io/v1alpha1"
kind: MachineDeployment
metadata:
  name: my-metal3-machine
  namespace: kube-system
spec:
  paused: false
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 0
  selector:
    matchLabels:
      name: foo
  template:
    metadata:
      labels:
        name: foo
    spec:
      providerSpec:
        value:
          sshPublicKeys:
            - "<< YOUR_PUBLIC_KEY >>"
          cloudProvider: "metal3"
          cloudProviderSpec:
            BMCAddress: "redfish+https://198.2.2.2"
	          BMCUser: "admin"
	          BMCPassword: "admin1234"
	          ImageURL: "https://35.35.35.35/ubuntu/ubuntu-18.04"
	          ImageChecksum: "https://35.35.35.35/ubuntu/ubuntu-18.04.md5"
            kubeconfig:
              value: '<< KUBECONFIG >>'
          # os will be ignored for metla3 since specific image url will be used
          operatingSystem: "ubuntu"
          operatingSystemSpec:
            distUpgradeOnBoot: false
            disableAutoUpdate: true
      versions:
        kubelet: "1.16.1"